SUITES = [
    ('test_boundary_detector.py', '边界检测器'),
    ('test_instance_merger.py', '实例合并'),
    ('test_node_classifier.py', '节点分类器'),
    ('test_semantic_naming.py', '语义命名'),
    ('test_position_conflict.py', '位置冲突检测'),
    ('test_zindex_layer_order.py', 'z-index 层级顺序'),
    ('test_moly_wrapper_css.py', 'CC wrapper CSS 剥离'),
    ('test_cc_leaf_and_variant.py', 'CC 叶子组件 + variant'),
    ('test_token_revert_and_wrapper.py', 'Token 反转 + wrapper'),
    ('test_apply_landing.py', '拆分落地集成'),
    ('test_section_root_strip.py', 'Section 根节点 absolute→flow + CC 组件覆写'),
    ('test_inline_root_strip.py', 'Inline node 根节点 absolute→flow'),
    ('test_image_composition.py', '图片合成检测 + 整帧导出'),
    ('test_validate_split_layer1.py', 'validate_split Layer 1 base class 回退'),
    ('test_validate_split_layer5.py', 'validate_split Layer 5 merged 节点跳过'),
    ('test_leaf_css_strip.py', 'Leaf CSS 剥离：位置冲突/%尺寸 + 重复 padding + overflow'),
    ('test_code_connect.py', 'Code Connect 解析 + Snippet Props 提取'),
    ('test_props_inference.py', 'Props 推断（boolean/variant/text/instance-swap）'),
]
